version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: mqtt
      POSTGRES_HOST_AUTH_METHOD: trust
      TZ: 'America/Sao_Paulo'
      PGTZ: 'America/Sao_Paulo'

    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    
    networks:
      - default
  
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_DEBUG = 'true'
    restart: on-failure

networks:
  default:
    name: pg

volumes:
  db-data:

